# Configurazione di Rete del Cluster Raft

# L'indirizzo IP del PC su cui stai eseguendo questo file (usato dal Server per esporsi)
my.ip=172.20.10.3

# La lista di TUTTI gli IP dei PC che fanno parte del cluster, separati da virgola
# (Usata sia dai Server per l'UDP, sia dai Client per l'RMI Race)
cluster.ips=172.20.10.2,172.20.10.3,172.20.10.4
